# ValNet is built on top of yolov8-seg. This file is used alongside OmegaConf.
# Not all options may be altered here; you may need to look into ULtralytics configuration docs

data:
  config: 'configs/xp12.yaml'
  num_classes: 1
  image_size: 640
optim:
  initial_lr: 0.01
  final_lr: 0.0001
  momentum: 0.937
  weight_decay: 0.0005
yolov8_checkpoint: 'checkpoints/yolov8s-seg.pt'
train:
  epochs: 2000
  batch_size: 24
  num_workers: 24 # num. of workers PER dataloader
  save_freq: 100
  val_freq: 5
  logdir: 'results/xtrack_logdir'
